### ISSUE TITLE
The site shows wrong current active page

### ISSUE THREAD

**Issue by anurag0singh** [khannakshat7/Elektra#10]
I have checked it with other pages than the home one. Initially, the page does not show the currently active page with a blue highlight but after scrolling down and going up again it always highlights the home in blue no matter on which page you actually are. I have attached a screenshot for reference.

Assign this to me under GSSOC'21.
![Screenshot (127)_LI](https://user-images.githubusercontent.com/71708571/110424194-69b1b300-80c8-11eb-95a2-b0919a11e8df.jpg)

**Comment by khannakshat7** [comment]
Ok assigning the issue to you @anurag0singh
