### ISSUE TITLE
[GSSOC'21] forgot password should be with login not with sign up.

### ISSUE THREAD

**Issue by shonali2600** [khannakshat7/Elektra#100]
## **Describe the bug**

Currently **forgot password** option is with sign up, It should be with login. Also, the spelling is wrong.

## **Possible solution**

I'll place it in the right place by correcting the typo. 

## **Screenshots**

![elektra](https://user-images.githubusercontent.com/57946528/111633643-ba898000-881b-11eb-926e-e1eb5497d5a7.png)

**Comment by khannakshat7** [comment]
Ok Go ahead...

**Comment by shonali2600** [comment]
@khannakshat7 sir please add the GSSOC label and level to this issue, and as you told me to go ahead I started working on this issue but you haven't assigned this issue to me. So please assign it to me.

**Comment by shonali2600** [comment]
@khannakshat7  sir, I've made the required changes, kindly review the code.
