### ISSUE TITLE
[Feature] [GSSOC' 21] Adding Facebook/Google login to the project

### ISSUE THREAD

**Issue by Aditya201551** [khannakshat7/Elektra#103]
## **Is your feature request related to a problem? Please describe.**

- It's been found that the project does not have any social login such as Facebook or Google, and sometimes it can really be frustrating as time-consuming to log in manually with the signup form.

## **Describe the solution you'd like**

- I would like to add Facebook(Can add google too if you say me) login to the app using allauth

**Comment by khannakshat7** [comment]
Ok go for it

**Comment by Aditya201551** [comment]
@khannakshat7 please assign me this task so I can start working on it
