### ISSUE TITLE
[GSSoC'21] Responsiveness of preloader in mobile version

### ISSUE THREAD

**Issue by arpit456jain** [khannakshat7/Elektra#109]
## **Describe the bug**

Preloader is not responsive in small screen like mobile  It is looking something like this...
<img width="960" alt="p5" src="https://user-images.githubusercontent.com/55352601/111864502-3d7b1980-8987-11eb-8058-fce7d40fd892.png">

## **Possible solution**

I can make it responsive , i am a gsoc participant please assign this to me I will fix it within a hour
## **Screenshots**

- If applicable, add screenshots to help explain your problem.
After solving this issue it will look like this..
<img width="960" alt="s1" src="https://user-images.githubusercontent.com/55352601/111864543-7a471080-8987-11eb-8c7b-d5c5cd37b440.png">

**Comment by khannakshat7** [comment]
Ok go for it

**Comment by arpit456jain** [comment]
sir please add the label of gsoc'21 as I am gsoc'21 participant

**Comment by arpit456jain** [comment]
@khannakshat7  sir please add the Gssoc'21 label so i can work on it as soon as possible.

**Comment by arpit456jain** [comment]
Thank You @CodesbyUnnati  Mam  I had already solve this issue in morning on my local machine i am just waiting for it to be assign to me I will PR within 2 min Kindly Review it . I will attach a video how it is looking.

**Comment by simranbhalla3** [comment]
Hi i am a gssoc participant , can i work on this issue?

**Comment by arpit456jain** [comment]
@simranbhalla3 I am sorry but this issue is already assigned to me and i had already solved it my PR is under reviewing process till Friday after that it will merge.
@CodesbyUnnati mam told me that someone PR is ready for merging after that my PR will be merged
