### ISSUE TITLE
[GSSoC'21] Responsiveness of map page 

### ISSUE THREAD

**Issue by arpit456jain** [khannakshat7/Elektra#110]
## **Describe the bug**
Responsive ness of map page is very drastic it is looking like this
<img width="960" alt="p2" src="https://user-images.githubusercontent.com/55352601/111864995-56d19500-898a-11eb-9019-125cea01d958.png">

## **Possible solution**
After Trying to solve this issue my code is looking like this
<img width="960" alt="sol2" src="https://user-images.githubusercontent.com/55352601/111865024-8385ac80-898a-11eb-9d96-c10c2c46f4cd.png">

- Describe the solution you thought of.
I am gsoc participant please assign me this issue i will improve the responsive ness of all pages whereever needed .
## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by khannakshat7** [comment]
Ok go ahead

**Comment by arpit456jain** [comment]
sir please add the label of gsoc .

**Comment by arpit456jain** [comment]
@khannakshat7  sir please add the Gssoc'21 label so i can work on it as soon as possible.

**Comment by arpit456jain** [comment]
@CodesbyUnnati may I create a PR?

**Comment by arpit456jain** [comment]
@khannakshat7  may i create a new PR.

**Comment by khannakshat7** [comment]
@arpit456jain Yeah sure

**Comment by arpit456jain** [comment]
ok @khannakshat7 sir  I will create a PR as soon as possible.

**Comment by arpit456jain** [comment]
@khannakshat7 please review my PR #125 .
