### ISSUE TITLE
Password Reset functionality

### ISSUE THREAD

**Issue by shreya9301** [khannakshat7/Elektra#115]
## **Is your feature request related to a problem? Please describe.**

There is a need for a password reset functionality when the user clicks "Forgot Password" during Log in.

## **Describe the solution you'd like**

As a GSSoc'21 participant , I would like to add the above mentioned functionality by adding a password reset form in the webapp.

**Comment by arpit456jain** [comment]
@CodesbyUnnati I am a Gssoc'21 participant and I want to try to do this if possible.

**Comment by coding-geek21** [comment]
@CodesbyUnnati I would like to work on this issue , please assign me

**Comment by arpit456jain** [comment]
@khannakshat7 I have added the feature of reset password I am uploading a video for showing it.

But currently I have not handle the exceptions and error success msg sice it will take some time to test this feature and its very difficult for me to test it alone .
so i was thinking to make a PR for this and create another issue for flashing msg and one issue for exception handling 

@khannakshat7 please let me know what do you think on it

**Comment by arpit456jain** [comment]
https://user-images.githubusercontent.com/55352601/117569643-41542e00-b0e4-11eb-8b2d-984f7379138a.mp4

**Comment by arpit456jain** [comment]
Although first email is checked if not exist it will not go further and if exist it will further and ask for otp if opt not match it will not go further if match it will go further i hope you are understanding

**Comment by arpit456jain** [comment]
Just 2 things are needed to be add 
1 . Some error success message flashing
2. Handling some exceptions 
I would like to make a PR for this issue and then i would like to create these 2 issue and solve one by one

The password reset features is working fine it will send otp to email and it will generate random 6 digit number every time

**Comment by arpit456jain** [comment]
@khannakshat7 may I create a PR for this issue ? Requesting to go through the above comments once

**Comment by arpit456jain** [comment]
@khannakshat7 please review my PR and before that please go through the above comments
