### ISSUE TITLE
Add recaptcha to all forms

### ISSUE THREAD

**Issue by khannakshat7** [khannakshat7/Elektra#124]
We want to add recaptcha to all the forms in the web app like the signup form and Contact Us form.

You can refer to the documentation from [https://www.google.com/recaptcha/about/](url)

**Comment by Mayank4git** [comment]
i want to work on this issue. Please assign this issue to me . as a beginner I am very keen to contribute

**Comment by ayushjha952** [comment]
Can you please assign it to me I want to work on it as GSSOC participant.

**Comment by nikhilkotiya** [comment]
@Can you please assign it to me I want to work on it.

**Comment by rijusougata13** [comment]
@khannakshat7  can you assign me on this?

**Comment by ayushjha952** [comment]
@khannakshat7 I have added recaptcha for contact form do I need to add recaptcha for login/signup form.

**Comment by khannakshat7** [comment]
@ayushjha952 Yes add recaptcha for signup form

**Comment by pallavi00021** [comment]
can I start working on this issue?? I'm gssoc'21 participant.  @khannakshat7

**Comment by rijusougata13** [comment]
i think its misleading everyone by this gsoc21 label...
