### ISSUE TITLE
Want to add dark mode

### ISSUE THREAD

**Issue by rupal121** [khannakshat7/Elektra#139]
## Proposal

(A clear and concise description of what the proposal is.)
Want to add a dark mode toggle button with a smooth transition

THIS IMAGE IS ONLY FOR REFERENCE PURPOSE.
![](https://res.cloudinary.com/practicaldev/image/fetch/s--93ZO737c--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/vu98mdraw6w7er1x8sg5.png)
. 

Kindly assign this issue to me @khannakshat7

**Comment by CodesbyUnnati** [comment]
Assigned! Go for it.

**Comment by shahbazalam07** [comment]
I also want to work on this issue

**Comment by rupal121** [comment]
Added Dark Mode. Kindly review @khannakshat7 @CodesbyUnnati

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by chazuttu** [comment]
I am GSSOC'21 Participant. Please assign this issue to me and review my PR for this issue. Thank you

**Comment by subhangi2731** [comment]
can u please assign this issue to me @khannakshat7

**Comment by arpit456jain** [comment]
Its already added @khannakshat7 
You can close this issue

**Comment by chazuttu** [comment]
I have already created the pull request. Assign her some other issue.
Thank you!!

**Comment by subhangi2731** [comment]
oh sorry @chazuttu I didn't see it sure agreed with @arpit456jain please close this issue then
