### ISSUE TITLE
Implementation of User's Feedback Model

### ISSUE THREAD

**Issue by sujoy-coder** [khannakshat7/Elektra#147]
#### Proposal

Hello @khannakshat7 @CodesbyUnnati I am a new contributor in this project.
I just want to implement a `Feedback` model for user's and also save the information in the database.
Please assign it to me under gssoc'21

Thank You :)

**Comment by khannakshat7** [comment]
@sujoy-coder Ok go ahead.

**Comment by arpit456jain** [comment]
@khannakshat7  its already done please close this
