### ISSUE TITLE
Navigation bar doesn't redirect to the correct section.

### ISSUE THREAD

**Issue by shonali2600** [khannakshat7/Elektra#148]
## **Describe the bug**
While clicking on Map, Dashboard, Announcement, and Feedback it redirects us to the login/signup page.

## **Possible solution**

I would like to fix this issue.

**Comment by simranbhalla3** [comment]
I am a Gssoc participant , please assign me this issue.

**Comment by khannakshat7** [comment]
@shonali2600 That's not a bug. It is done so that first the user has to login then he/she can use the services.

**Comment by shonali2600** [comment]
Okay, I got it. Then we can also add some text so as to inform the user about this, as it's a bit confusing.
