### ISSUE TITLE
[Gssoc'21] 404 page 

### ISSUE THREAD

**Issue by arpit456jain** [khannakshat7/Elektra#152]
## **Is your feature request related to a problem? Please describe.**

There was no 404 page in templates.
<img width="960" alt="p11" src="https://user-images.githubusercontent.com/55352601/114023329-5ee96a00-9890-11eb-9a97-fb5b9874365a.png">

## **Describe the solution you'd like**
I want to make a 404 page for the website
- A clear and concise description of what you want to happen.

**Comment by iaryangoyal** [comment]
Can i do this?

**Comment by khannakshat7** [comment]
@arpit456jain Go ahead
