### ISSUE TITLE
[Gssoc'21] Back to top button

### ISSUE THREAD

**Issue by arpit456jain** [khannakshat7/Elektra#153]
## **Is your feature request related to a problem? Please describe.**

There is no back to top button in website

## **Describe the solution you'd like**
I would like to add the back to top button on every page

**Comment by iaryangoyal** [comment]
can I do this?

**Comment by arpit456jain** [comment]
@CodesbyUnnati can I start working on this??

**Comment by khannakshat7** [comment]
@arpit456jain Go for it
