### ISSUE TITLE
[Gssoc21] Crucial bug in feedback 

### ISSUE THREAD

**Issue by arpit456jain** [khannakshat7/Elektra#157]
## **Describe the bug**

1.Well when i filled all the information and click on submit it just open the feedback page on a new tab
2 It is not saving my feedback .
Please watch this video for better understanding my issue.

https://user-images.githubusercontent.com/55352601/114299598-d52cdd00-9ad9-11eb-9992-9260d3383cf1.mp4

## **Possible solution**
It should show success or any warning message on the same page.
and rating selected should be saved.

**Comment by arpit456jain** [comment]
@khannakshat7 kindly look into this issue its a serious bug

**Comment by arpit456jain** [comment]
@CodesbyUnnati kindly assign me this issue

**Comment by khannakshat7** [comment]
@arpit456jain Go ahead

**Comment by arpit456jain** [comment]
@khannakshat7 kindly review my PR
