### ISSUE TITLE
[Gssoc'21] Check if username is already exists in front-end without submitting form

### ISSUE THREAD

**Issue by arpit456jain** [khannakshat7/Elektra#160]
I would like to give it a try to add this feature in this website.
Benefits  : user can change his/her username at the time of creating account . There will be no duplicate username and email.
And this is checked at front-end no need to submit the form again and again.

**Comment by arpit456jain** [comment]
@CodesbyUnnati @khannakshat7 there is lot of mess in the login/sign up functionality.
<img width="960" alt="e" src="https://user-images.githubusercontent.com/55352601/114474469-f1349980-9c13-11eb-8bb2-86fb3752d5d7.png">

**Comment by arpit456jain** [comment]
@CodesbyUnnati Actually may some one just exchange the names there is a lot of confusion in backend 
its taking email in the name of username
and taking username in the name of email😢
I had spent past 2 hours in finding why my code is not working properly but actual problem is in website code

 I will upload a video on you tube and will share the link here
https://youtu.be/fKHNiV7bccs

**Comment by arpit456jain** [comment]
If you had watched the video you will surely understand that 
According to your current code
Email is going in table username
And
Username is going in table email

**Comment by khannakshat7** [comment]
@arpit456jain Yes I understood the problem. U can change it and make the changes in ur PR

**Comment by arpit456jain** [comment]
> @arpit456jain Yes I understood the problem. U can change it and make the changes in ur PR

@khannakshat7  @CodesbyUnnati  
i have solved this issue and uploaded a video for brief description  of problem and solution .
kindly review my PR
