### ISSUE TITLE
Add a hover effect on know more button in the home page

### ISSUE THREAD

**Issue by barsha119** [khannakshat7/Elektra#163]
## Proposal

I want to add hover effect on know more button exactly like the login/signup button in the header tab ,  using css.
Please consider this under GSSOC'21.

**Comment by Amulya310** [comment]
Kindly consider assigning this issue to me under GSSOC '21.

**Comment by CodesbyUnnati** [comment]
Please find some valid issues, Adding hover property to one button is not an issue.
