### ISSUE TITLE
[Gssoc'21] Bug in contact us form

### ISSUE THREAD

**Issue by arpit456jain** [khannakshat7/Elektra#164]
## **Describe the bug**
In phone number field if i give any text it is not throwing any error 

## **Possible solution**
It should throw a error "Enter a valid mobile number"

**Comment by PrabhatP2000** [comment]
Hello arpit, I have already fixed this issue by making the phone type from text to number.
You can close the issue.

**Comment by arpit456jain** [comment]
> Hello arpit, I have already fixed this issue by making the phone type from text to number.
> You can close the issue.

But still if i enter any text it will accept it i had tried it yesterday.🤔

**Comment by PrabhatP2000** [comment]
> > Hello arpit, I have already fixed this issue by making the phone type from text to number.
> > You can close the issue.
> 
> But still if i enter any text it will accept it i had tried it yesterday.🤔

Its because my pull request is not merged yet.

**Comment by khannakshat7** [comment]
@PrabhatP2000 Yeah it will be merged soon
