### ISSUE TITLE
To add mandatory field option in login page

### ISSUE THREAD

**Issue by sreetu** [khannakshat7/Elektra#166]
## Proposal

(A clear and concise description of what the proposal is.)
In the login section, if one does not fill the details like email and password and click on submit then, it is redirecting to the next webpage. I want to fix this issue by adding required fields tag in the login.html file.
I am a participant at GSSOC'21, requesting admins to assign me this issue.

**Comment by arpit456jain** [comment]
@khannakshat7  if its open then please assign me
