### ISSUE TITLE
Adding a dark mode to the website

### ISSUE THREAD

**Issue by Tushar1337** [khannakshat7/Elektra#170]
Hi, I'm trying to add a dark mode to the website, I'm already ready with the code and I have some screenshots below but the only problem I have is I currently have a toggle for it but whenever I refresh it goes to the default light mode is there any way I can keep that javascript function in cookies or cache or something like that so that it stays even when I refresh it? I'm a GSSOC participant can you assign this to me and tell me what I can do because I'm really new to javascript.

![image](https://user-images.githubusercontent.com/53913018/115271029-8a0a6e00-a15a-11eb-8d7b-0a7e5a3f71ea.png)
![image](https://user-images.githubusercontent.com/53913018/115271119-a0b0c500-a15a-11eb-92ee-69288c85a22a.png)
![image](https://user-images.githubusercontent.com/53913018/115271174-b32afe80-a15a-11eb-925a-d9709b5a26d9.png)

**Comment by arpit456jain** [comment]
@Tushar1337 can i work on this issue now if you are done with this.?

**Comment by arpit456jain** [comment]
@khannakshat7 please assign me this issue

**Comment by arpit456jain** [comment]
@khannakshat7 kindly assign me this issue

**Comment by arpit456jain** [comment]
@CodesbyUnnati can you please assign me this issue
