### ISSUE TITLE
feedback Page

### ISSUE THREAD

**Issue by RuchiGitHu** [khannakshat7/Elektra#173]
## **Is your feature request related to a problem? Please describe.**

- I want to add Feedback page for website.

## **Describe the solution you'd like**

- I have made many designs and web pages for websites. I can do make it, so, please assign this issue to me under gssoc21.
- I will use HTML and CSS to make it happen.

**Comment by RuchiGitHu** [comment]
Please assign this issue to me @khannakshat7

**Comment by arpit456jain** [comment]
I think there is already a feedback page there @RuchiGitHu

**Comment by RuchiGitHu** [comment]
> I think there is already a feedback page there @RuchiGitHu

I thought it's an contact us page because that only page is showing in all navbar buttons.
Looking forward for your reply on it...

**Comment by arpit456jain** [comment]
> > I think there is already a feedback page there @RuchiGitHu
> 
> I thought it's an contact us page because that only page is showing in all navbar buttons.
> Looking forward for your reply on it...

you have login first to access feedback page.

you can see the feedback page in this video 

https://user-images.githubusercontent.com/55352601/115946580-ce419980-a4df-11eb-91a9-9d86267356a4.mp4

**Comment by RuchiGitHu** [comment]
> > > I think there is already a feedback page there @RuchiGitHu
> > 
> > 
> > I thought it's an contact us page because that only page is showing in all navbar buttons.
> > Looking forward for your reply on it...
> 
> you have login first to access feedback page.
> 
> you can see the feedback page in this video
> 
>  final.feedback.mp4

Ok, thanks for your time to clear this things....
Can you please give your important clarification about Map option in navbar.
I am looking forward to add map over there....Can I create another issue for this if this is valid?

**Comment by arpit456jain** [comment]
I don't think its an good idea because there is already a map on map page 😅

**Comment by RuchiGitHu** [comment]
> I don't think its an good idea because there is already a map on map page 😅

Sorry to interrupt you but from README page when I load a live website it showing feedback page in map option of navbar.
![image](https://user-images.githubusercontent.com/71754179/115964317-7a679c80-a541-11eb-834b-528e6a464794.png)

**Comment by arpit456jain** [comment]
As i told you earlier you have to login first for accessing any page.

Try to register , then login and then you can see all of them

**Comment by RuchiGitHu** [comment]
> As i told you earlier you have to login first for accessing any page.
> 
> Try to register , then login and then you can see all of them

Oh, thanks for your support and guidance, looking forward to contribute in this project.
Thanks again....
