### ISSUE TITLE
Remove contact title from the FOOTER

### ISSUE THREAD

**Issue by tanishq-arya** [khannakshat7/Elektra#175]
## **Describe the bug**

For a better UI, the contact title seems a bit odd. 

## **Possible solution**
Just remove the section title from the contact section

## **Screenshots**
![image](https://user-images.githubusercontent.com/77333275/115821597-b820d400-a420-11eb-9f42-e40369009a22.png)

**Comment by tanishq-arya** [comment]
Please assign me this issue under gssoc

**Comment by CodesbyUnnati** [comment]
Do you want to remove the "Contact" title from the footer?

**Comment by tanishq-arya** [comment]
Yes. And if you want me to do any changes to the footer I can implement that too.

**Comment by tanishq-arya** [comment]
What if we add  a card effect to the footer like the header then it will look better.

**Comment by CodesbyUnnati** [comment]
A simple footer looks good, I think we don't need to change it.

**Comment by tanishq-arya** [comment]
Okay
