### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [khannakshat7/Elektra#177]
I want to add scroll-top arrow to website that will allow the user to directly reach at the top of the page.

[GSSOC'21]

Please assign me this issue @khannakshat7 @CodesbyUnnati

**Comment by arpit456jain** [comment]
There is already one pr for the same and i had also created a issue for this although its not assigned to me yet you can comment on that issue. If that issue Assign then it will be ok for me..


Lets try together to not create multiple issues for the same.🙂
