### ISSUE TITLE
Improving the home page

### ISSUE THREAD

**Issue by PranavChauhan22** [khannakshat7/Elektra#187]
I want to add cool animations and transitions in home page so that site must also have some dynamic content along with static content plus it will also give user a better experience about the webpage

**Comment by PranavChauhan22** [comment]
Admins should i proceed for it

**Comment by khannakshat7** [comment]
@PranavChauhan22 Great !! I want to see some cool animations

**Comment by PranavChauhan22** [comment]
I have improved the scroll speed and also added scroll animation in cards.

**Comment by taneeshaa15** [comment]
@khannakshat7 Please assign this issue to me.
