### ISSUE TITLE
Linting the code and make the code prettier

### ISSUE THREAD

**Issue by subhangi2731** [khannakshat7/Elektra#188]
I want to set up Eslint in the project and make the code prettier. Please assign this issue to me @khannakshat7

**Comment by khannakshat7** [comment]
@subhangi2731 Go ahead

**Comment by subhangi2731** [comment]
@khannakshat7 please add the level tag

**Comment by khannakshat7** [comment]
@subhangi2731 Any updates on it?

**Comment by subhangi2731** [comment]
@khannakshat7 yes I am working on it I will create a pr by tomorrow
