### ISSUE TITLE
Sign up error 

### ISSUE THREAD

**Issue by dhruv-rajput** [khannakshat7/Elektra#195]
## **Describe the bug**

Hello contributors I was trying to signup on the site and got a error message of "Sever error (500)"  instead. Can you please check that out.

## **Screenshots**
![101](https://user-images.githubusercontent.com/55194861/118638847-e2359e00-b7f4-11eb-88da-b65b6a67fdc8.PNG)

**Comment by khannakshat7** [comment]
@dhruv-rajput Thanks for letting us know. It is a deployment error and will be solved soon
