### ISSUE TITLE
Feature to download feedback data as csv file

### ISSUE THREAD

**Issue by arpit456jain** [khannakshat7/Elektra#205]
currently there is no admin dashboard i guess so i can't add a button but i can write the backend for it .

you just have to go to 
/downloadFeedback

and this will download a csv file for you having data of feedback

**Comment by khannakshat7** [comment]
@arpit456jain There is no need for this as django admin has a module to download DB data in CSV file

**Comment by khannakshat7** [comment]
If you want to can implement that django admin module

**Comment by arpit456jain** [comment]
Well i don't know about that but i will try it

**Comment by arpit456jain** [comment]
@khannakshat7 i had implemented it successfully .
have a look

https://user-images.githubusercontent.com/55352601/119626408-cea7ba00-be28-11eb-92d0-382355b4d2da.mp4

can I make a PR for this.?

**Comment by arpit456jain** [comment]
I used the module 
import_export == 2.5.0

**Comment by khannakshat7** [comment]
Go ahead and make pr
