### ISSUE TITLE
Email warning if login fails more than 5 times

### ISSUE THREAD

**Issue by arpit456jain** [khannakshat7/Elektra#206]
Let say some one is trying to login in my account and he fails 5 times . So i should get an warning 
email that someone is trying to login in your account .

**Comment by arpit456jain** [comment]
@khannakshat7 please assign me this.
I think its a really good issue for security purpose

**Comment by arpit456jain** [comment]
@khannakshat7 can i make a PR for this?

**Comment by khannakshat7** [comment]
@arpit456jain How are you planning to develop it? Please come up with a optimistic solution and discuss

**Comment by arpit456jain** [comment]
> @arpit456jain How are you planning to develop it? Please come up with a optimistic solution and discuss

I had already done this.
I make a dictionary in python and i am checking every time when someone trying to login if it success then no problem.
But if it fails i do dict[user] = 1 if it's not present in dictionary and if its present i will do dict[user] += 1.
And if this Value increase than 5 i will send email and if user login before it reaches to 5 i will set value to 0

**Comment by arpit456jain** [comment]
@khannakshat7 if you want more optimization then i can remove that key from dictionary when user login successfully before reaching 5
