### ISSUE TITLE
Adding contact logo at the home page

### ISSUE THREAD

**Issue by kumarishalini6** [khannakshat7/Elektra#207]
## Proposal
I want to add logo of contact us in home page as side logo and add hover over it like:-

![InkedJagrati _ Home - Personal - Microsoft​ Edge 5_22_2021 02_21_33 PM_LI](https://user-images.githubusercontent.com/69043944/119220739-6f4c5180-ba98-11eb-9cf2-713a99106a16.jpg)

**Comment by kumarishalini6** [comment]
I want to work on this issue under GSSoC'21.

**Comment by khannakshat7** [comment]
@kumarishalini6 Go ahead

**Comment by kumarishalini6** [comment]
can you please add labels.

**Comment by kumarishalini6** [comment]
please review my PR

**Comment by kumarishalini6** [comment]
I have send PR please  have a look
