### ISSUE TITLE
Hover effect on navbar

### ISSUE THREAD

**Issue by kumarishalini6** [khannakshat7/Elektra#208]
## **Is your feature request related to a problem? Please describe.**
I want to give some hover effect on navbar like:-
when someone hover on the navbar items a line appear at the bottom of the items  . 
Can i work on this issue under GSSoC'21.

**Comment by khannakshat7** [comment]
@kumarishalini6 Can u try to come up with some other enhancements so that you can contribute in a better way.

**Comment by kumarishalini6** [comment]
Ok

**Comment by kumarishalini6** [comment]
can you please add labels.
