### ISSUE TITLE
Improving all the buttons available in the projects

### ISSUE THREAD

**Issue by kumarishalini6** [khannakshat7/Elektra#215]
## Proposal
I want to improve buttons 
![InkedElektra _ Electricity Outage prediction - Personal - Microsoft​ Edge 5_23_2021 10_55_55 AM_LI](https://user-images.githubusercontent.com/69043944/119249430-fc4ce480-bb44-11eb-94ff-8bdd58e11c72.jpg)
![InkedElektra _ Electricity Outage prediction - Personal - Microsoft​ Edge 5_23_2021 10_56_54 AM_LI](https://user-images.githubusercontent.com/69043944/119249435-0b339700-bb45-11eb-82cd-8c6ed51cb8e4.jpg)
![InkedElektra _ Electricity Outage prediction - Personal - Microsoft​ Edge 5_23_2021 10_57_42 AM_LI](https://user-images.githubusercontent.com/69043944/119249440-125aa500-bb45-11eb-87da-355792212df6.jpg)

**Comment by kumarishalini6** [comment]
Can i work on this issue under GSSoC'21

**Comment by khannakshat7** [comment]
@kumarishalini6 Go ahead and come up with a cool button
