### ISSUE TITLE
add documentation for setting up eslint and making the code prettier

### ISSUE THREAD

**Issue by subhangi2731** [khannakshat7/Elektra#219]
I will write all the steps as how the eslint is setup and how the code is made prettier and which files are modified and enhanced

**Comment by subhangi2731** [comment]
@khannakshat7 please assign me this issue

**Comment by khannakshat7** [comment]
@subhangi2731 Any update?

**Comment by subhangi2731** [comment]
@khannakshat7 i am working on this will make a pr by tomorrow
