### ISSUE TITLE
Improving the form card

### ISSUE THREAD

**Issue by kumarishalini6** [khannakshat7/Elektra#227]
The form card are so simple i want to give some border radius , shadow. And the background is not looks good.
![Elektra _ Electricity Outage prediction and 1 more page - Personal - Microsoft​ Edge 5_28_2021 12_33_09 AM](https://user-images.githubusercontent.com/69043944/119882789-433b3100-bedb-11eb-9ccf-127a1b8be55a.png)

**Comment by kumarishalini6** [comment]
@khannakshat7 Can i work on this issue

**Comment by JAgrit20** [comment]
@kumarishalini6, you shall start working on this

**Comment by kumarishalini6** [comment]
@khannakshat7 please review my PR
