### ISSUE TITLE
Adding Dark Mode 

### ISSUE THREAD

**Issue by prisha-srivastava** [khannakshat7/Elektra#27]
I would like to add the dark mode feature to the website. Please assign me this issue as part of GSSOC'21.

**Comment by prisha-srivastava** [comment]
@khannakshat7 Due to some reason, I won't be able to work on this issue anymore. Please unassign me from this issue. I hope somebody else can work on it.

**Comment by thesakshipandey** [comment]
Can you assign me this issue, I'll be able to do this

**Comment by khannakshat7** [comment]
@thesakshipandey You can contribute to this

**Comment by thesakshipandey** [comment]
Thanks alot!

**Comment by MadHawkx** [comment]
Hi, @khannakshat7 and @thesakshipandey  

If more workforce is needed in this issue, I would like to assist.

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by MayankBeck** [comment]
I would like to work on this issue under GSSoC 21. please assign this task to me. My discord id in GSSOC(GS)'s server is Mayank(P)#9695 .

**Comment by subhangi2731** [comment]
@khannakshat7 please assign me this issue I want to work

**Comment by khannakshat7** [comment]
#194
