### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by avishmehta68710** [khannakshat7/Elektra#29]
![image](https://user-images.githubusercontent.com/69706506/110591157-2459b800-8192-11eb-883a-d1494ab211f2.png)

**Comment by khannakshat7** [comment]
@avishmehta68710

**Comment by avishmehta68710** [comment]
ya i did pip install mysqlclient

**Comment by tanishq-arya** [comment]
Check this 
https://github.com/khannakshat7/Elektra/issues/35#issuecomment-795470004
