### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by rohank2502** [khannakshat7/Elektra#31]
In Section The Problem 
In India, there is a problem of Electricity Outage every now and then, especially in some states. So,Elektra is an ML based Web App by which will be use for real-time monitoring of theElectricity Outages in an area and display them in form of maps, Dashboard with pie charts, line graph, etc, where people will be able to report the electricity outages in their area of the city, in response to which the Electricity Department will try to track and solve the fault and we are able to monitor and predict the frequency of Electricity Outage in our area or in any part of the city. 

There are some error which i will like to fix as the wording dont make sence somewhere i will like to fix that issue after getting assigned !!

**Comment by pranjalg13** [comment]
Can i work on this??

**Comment by shreya9301** [comment]
I would like to work on this issue under gssoc'21 .

**Comment by rohank2502** [comment]
> 
> 
> I would like to work on this issue under gssoc'21 .

I am working on this sorry @shreya9301
