### ISSUE TITLE
issue with running the website

### ISSUE THREAD

**Issue by Sloth-Panda** [khannakshat7/Elektra#35]
Hey after installing all the requirements I ran python manage.py runserver(even after migrating and running) but it is showing me this issue, can you upadate your readme explaining how to run this project on the server?! 
![Screenshot (171)](https://user-images.githubusercontent.com/70213384/110634410-eed3bf80-81cf-11eb-9e3a-e6a37cdb727a.png)

**Comment by Sloth-Panda** [comment]
@khannakshat7

**Comment by tanishq-arya** [comment]
Hey I had a similar issue. I can help with this

**Comment by Sloth-Panda** [comment]
> Hey I had a similar issue. I can help with this

yaya tell here  @tanishq-arya

**Comment by tanishq-arya** [comment]
@Sloth-Panda is it working now ?

**Comment by Sloth-Panda** [comment]
let me check @tanishq-arya do i need to install XAMPP?

**Comment by tanishq-arya** [comment]
I don't think so just run your SQL and create a database. I guess that should work.

**Comment by Sloth-Panda** [comment]
> You have to modify the settings.py
> Enter your username, password and the database name(by default it is elektra) if you don't have it then create it. I ran SQL using XAMPP so I'm good to work on it now

can you explain a bit more what user name and password is this and what I need to create?? @tanishq-arya

**Comment by tanishq-arya** [comment]
Are you on gssoc'21 discord server ?

**Comment by Sloth-Panda** [comment]
> Are you on gssoc'21 discord server ?

yes

**Comment by tanishq-arya** [comment]
Add me there

**Comment by Sloth-Panda** [comment]
id

**Comment by tanishq-arya** [comment]
yes Sure

**Comment by tanishq-arya** [comment]
Sorry I left in between. Here's the quickest solution.
1. Install XAMPP
2. Open XAMPP admin
3. Start SQL on XAMPP
4.  Make a new user
5. Create a database with name elektra
6. Update settings.py
7. Run python manage.py runserver 
![Screenshot (944)](https://user-images.githubusercontent.com/77333275/110642512-1713ec00-81d9-11eb-83d1-4d13b3d460c6.png)
