### ISSUE TITLE
Google Authentication

### ISSUE THREAD

**Issue by sneha-nitdgp** [khannakshat7/Elektra#36]
Google authentication would allow the users to sign up by just a single click, instead of manually signing up and logging in. I'd love to add this feature.
@khannakshat7 Can you please assign this to me?

**Comment by nikhilkotiya** [comment]
@khannakshat7  Can i contribute in this issue?

**Comment by pranjalg13** [comment]
@sneha-nitdgp Are you working on this?? If not, I can take this issue.

**Comment by sneha-nitdgp** [comment]
@pranjalg13 Yes, I'm working on it

**Comment by subhangi2731** [comment]
@CodesbyUnnati @khannakshat7 there hasnt been any pr made please assign me this issue

**Comment by khannakshat7** [comment]
#103

**Comment by khannakshat7** [comment]
#121
