### ISSUE TITLE
[GSSoC '21] Create back to top button

### ISSUE THREAD

**Issue by amrzaki2000** [khannakshat7/Elektra#37]
Hello,
I'd like to create a back-to-top button as GSSoC 2021 contribution.

**Comment by CodesbyUnnati** [comment]
> Hello,
> I'd like to create a back-to-top button as GSSoC 2021 contribution.

Sure, go for it.

**Comment by rk05-lenavo** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?

**Comment by vatsalar** [comment]
I am interested in contributing to the above issue. Kindly assign me this issue.

**Comment by CodesbyUnnati** [comment]
Assigned
