### ISSUE TITLE
OperationalError at /register/

### ISSUE THREAD

**Issue by 4doctorstrange** [khannakshat7/Elektra#4]
Hello maintainers, when I was trying to sign up in the Electra, I was redirected to the exception page and it says 2002, "Can't connect to local MySQL server through socket '/cloudsql/elecktra:us-central1:elecktra-instance' (111)". 
![electra](https://user-images.githubusercontent.com/43610647/109426038-6572ff00-7a11-11eb-85bf-a2f56ae0f44b.JPG)

**Comment by khannakshat7** [comment]
@4doctorstrange Thanks for letting us know. We have fixed the issue. Please check again
