### ISSUE TITLE
[GSSoC '21] Dsahboard header bug

### ISSUE THREAD

**Issue by amrzaki2000** [khannakshat7/Elektra#50]
Hello,
On dashboard page, the header button does not show on mobile.
I'd like to fix this bug as part of my GSSoC participation.
![image](https://user-images.githubusercontent.com/62449903/110914450-0ff6f600-831f-11eb-9d94-84fef0d4d187.png)

**Comment by Ankita297** [comment]
Can i work on this @CodesbyUnnati ?

**Comment by khannakshat7** [comment]
@Ankita297 Ok u can contribute to this

**Comment by arpit456jain** [comment]
@khannakshat7 please assign me this
