### ISSUE TITLE
Backend for Contact us form

### ISSUE THREAD

**Issue by khannakshat7** [khannakshat7/Elektra#56]
## **Is your feature request related to a problem? Please describe.**
We have created the frontend for the Contact us form using HTML and CSS. Add the Backend code to handle the response after submit button.

## **Describe the solution you'd like** 
2. You need to add a function in views.py to send an email to the admin.
3. Add the path/route to the url.py file.

**Comment by anurag0singh** [comment]
@khannakshat7  I can work on this but where is the HTML and CSS file.
Assign this to me under GSSOC'21.

**Comment by Tushar1337** [comment]
I'd like to work on this I have a great experience with Django and created multiple websites with it can you assign this to me I'm a gssoc 21 participant

**Comment by shivaamm** [comment]
Hey!! Contact page is on all the pages including the homepage so wouldn't be good if a separate page is made for the contact ? 
On homepage a chatting bot can be added which will take us to the contact form if the user problem is not solved by the bot.

**Comment by khannakshat7** [comment]
@shivaamm Yes create a new seperate page for contact

**Comment by anurag0singh** [comment]
@khannakshat7 sir you have assigned us all. Who is supposed to work not this?

**Comment by shivaamm** [comment]
> @shivaamm Yes create a new seperate page for contact

Alright Thanks

**Comment by khannakshat7** [comment]
> @khannakshat7 sir you have assigned us all. Who is supposed to work not this?

Anyone who raises the first PR without conflicts will be merged

**Comment by pranjalg13** [comment]
@khannakshat7 I have pulled the changes, but there is no contact form? It the form remaining to be merged?

**Comment by khannakshat7** [comment]
> @khannakshat7 I have pulled the changes, but there is no contact form? It the form remaining to be merged?

Yes wait for some time it will be merged soon

**Comment by Kashish-2001** [comment]
I'm on it. I am doing the Backend part. Please assign this to me under gssoc21.

**Comment by Kashish-2001** [comment]
@khannakshat7 I'm on it. I am doing the Backend part. Please assign this to me under gssoc21.
