### ISSUE TITLE
Hompage know more button

### ISSUE THREAD

**Issue by shivaamm** [khannakshat7/Elektra#62]
## **Describe the bug**
know more button on the homepage 

- - this button takes to login page and asks to login again even if we are logged in

## **Possible solution**
We can direct the page to it's next section on the same page where it's described what this project is about.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/59584173/111022010-186e3000-83f6-11eb-9340-6a5d3525d64e.png)

**Comment by shivaamm** [comment]
pls assign this to me if you're fine with possible solution or if you have a better suggestion then pls discuss :)

**Comment by khannakshat7** [comment]
This issue is already solved #39

**Comment by shivaamm** [comment]
> This issue is already solved #39

okay thanks
