### ISSUE TITLE
Feedback form error

### ISSUE THREAD

**Issue by nikhilkotiya** [khannakshat7/Elektra#7]

**Comment by khannakshat7** [comment]
@nikhilkotiya Can you please provide the description for the error so that I can assign you the issue

**Comment by nikhilkotiya** [comment]
@khannakshat7  When i submitting Feedback  form then showing error csrf_token  is missing and when i check feedback.html template then  i found csfd token is missing

**Comment by khannakshat7** [comment]
@nikhilkotiya You can fix the bug it is easy

**Comment by khannakshat7** [comment]
@nikhilkotiya are u facing any problems?

**Comment by nikhilkotiya** [comment]
yes i Push my code on branch nikhil and after that i create a pull from branch nikhil but i dont know what i have do next?

**Comment by khannakshat7** [comment]
Yes ur part is done. I'll review the code and merge if there are no errors

**Comment by nikhilkotiya** [comment]
Sry i dont know about git too much. I commit my code 3 time and pull request 2 times  so is there any eshu?

**Comment by khannakshat7** [comment]
No there is no issue with that

**Comment by nikhilkotiya** [comment]
OK what i have do next?

**Comment by khannakshat7** [comment]
We'll review and merge the code if it has no errors.

**Comment by nikhilkotiya** [comment]
Ok sir
