### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [khannakshat7/Elektra#73]
Hey! I would like to add the following in contributing.md
Add the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on this as a part of GSSOC'21

**Comment by CodesbyUnnati** [comment]
Hey, @khareyash05 I'm glad you are here to contribute to this repo, but the issue you have created is half resolved...as a person has created a welcome bot that does these things.
Also, I think there is no need to include the difference between Git and Github in the project Repo. And "how to clone" this repo part is already present in the Readme.
So, please look into other issues :)
