### ISSUE TITLE
The User title link gets stuck if we clicked on it.

### ISSUE THREAD

**Issue by pranjalg13** [khannakshat7/Elektra#74]
## Proposal
When the logged-in user clicks on the username along with some link(in the navbar) the hover effect remains and it doesn't go until refreshing the page. I added some styling to remove the ambiguity. 

Title
- [ Gssoc21]
- [level 1]

**Comment by CodesbyUnnati** [comment]
I didn't understand your issue, can u please explain it more clearly, or can u record and attach that part for better understanding.

**Comment by pranjalg13** [comment]
The main issue was **Welcome, username** was set as a <a tag href="#"> so if a user is on let's say feedback page and accidently clicks on the username, then both the links will be active and it doesn't go until refresh the page.
![dpubt2](https://user-images.githubusercontent.com/47600057/111030604-3a34da80-8429-11eb-9813-1133622a3b0c.JPG)
As shown in the image.

**Comment by pranjalg13** [comment]
@CodesbyUnnati I have updated the PR, where I have also included the updated image. It is like this:
![updated2](https://user-images.githubusercontent.com/47600057/111030717-d1019700-8429-11eb-8cff-eec984af36b4.JPG)
This code changed is more clear. Look into it.

**Comment by CodesbyUnnati** [comment]
Yes, now this looks fine. I'll assign this issue to you.
