### ISSUE TITLE
Linkedin authentication.

### ISSUE THREAD

**Issue by nikhilkotiya** [khannakshat7/Elektra#79]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.
Linkedin authentication would allow the users to sign up by just a single click. Save the time of the user for login.

**Comment by Pointdexter99** [comment]
Do we require only linkedin authentication system integration..?? Or can we give the option for google/facebook signups as well. In that case I'd like to add an issue for the same and start working on all three.
