### ISSUE TITLE
Update Readme.md and add steps to run the project locally

### ISSUE THREAD

**Issue by khannakshat7** [khannakshat7/Elektra#8]
- Add the steps to run Django Project locally. 
- This would help the contributors to set up project on the local system.
- Just add the commands to run in the terminal.
- The steps should include -
1. Installing Django in virtual environment.
2. Installing the dependencies.
3. Connecting project to MySQL database.
4. Migrating the project DB.
5. Create a superuser. 
6. Run the local server.

**Comment by anurag0singh** [comment]
Can I do this ?
Please assign me under GSSOC'21

**Comment by khannakshat7** [comment]
Yeah sure you can take up the issue. If you have doubts regarding commands you can ask here
I am assigning the issue to you.

**Comment by anurag0singh** [comment]
Thanks, @khannakshat7

**Comment by anurag0singh** [comment]
Which python version is this repo running on?

**Comment by khannakshat7** [comment]
We are using python 3.6

**Comment by anurag0singh** [comment]
Where is the databse @khannakshat7
