### ISSUE TITLE
Preloader 

### ISSUE THREAD

**Issue by nikhilkotiya** [khannakshat7/Elektra#91]
## **Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

## **Describe the solution you'd like**

- A clear and concise description of what you want to happen.
Adding Elektra logo as a preloader.

**Comment by Ankita297** [comment]
Can i work on this ?

**Comment by nikhilkotiya** [comment]
@Ankita297 i have already done this issue
